lalba/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from reservations import views as reservation_views
from contact import views as contact_views
from django.conf.urls import handler404
from . import views
from .views import error_404_view

handler404 = error_404_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(
        template_name='about.html'), name='about'),
    path('menu/', TemplateView.as_view(
        template_name='menu.html'), name='menu'),
    path('accounts/', include('allauth.urls')),
    path('reservations/',
         reservation_views.reservation_list, name='reservation_list'),
    path('reservations/new/',
         reservation_views.new_reservation, name='new_reservation'),
    path('reservations/report/<int:booking_id>/',
         reservation_views.reservation_report, name='reservation_report'),
    path('reservations/update/<int:booking_id>/',
         reservation_views.update_reservation, name='update_reservation'),
    path('reservations/<int:booking_id>/delete/',
         reservation_views.delete_reservation, name='delete_reservation'),
    path('contact/', contact_views.contact_view, name='contact'),

]

contact/models.py
from django.db import models


class ContactMessage(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    subject = models.CharField(max_length=100)
    email = models.EmailField()
    notes = models.TextField(max_length=500)
    responded = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    admin_response = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.email

contact/forms.py
from django import forms
from allauth.account.forms import LoginForm
from allauth.account.forms import SignupForm as AllauthSignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from .models import ContactMessage
from django.utils.translation import ugettext_lazy as _

User = get_user_model()

# Form for ContactMessage model
class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'subject', 'email', 'notes']

# Custom Signup form extending AllauthSignupForm
class CustomSignupForm(AllauthSignupForm):
    first_name = forms.CharField(max_length=30, label=_('First Name'))
    last_name = forms.CharField(max_length=30, label=_('Last Name'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

# Custom Login form extending AuthenticationForm
class CustomLoginForm(AuthenticationForm):
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = None

        if username and password:
            user = authenticate(username=username, password=password)

            if user is None:
                raise forms.ValidationError("Invalid username or password")

            self.user = user

        return self.cleaned_data

contact/views.py
from django.shortcuts import render
from .forms import ContactForm


# View function for the contact form
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact/success_message.html')
    else:
        form = ContactForm()

    return render(request, 'contact/contact_form.html', {'form': form})

contact/templates/contact/contact_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 mt-4">
            <h2 class="text-center mb-4"><i class="fas fa-comments"></i> How can we help you?</h2>
            <form method="post" class="mt-4">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Name:</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="id_subject">Subject:</label>
                    {{ form.subject }}
                </div>
                <div class="form-group">
                    <label for="id_email">Email:</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="id_notes">Notes:</label>
                    {{ form.notes }}
                </div>
                <button type="submit" class="btn btn-primary mb-4">SEND</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mt-4 text-center">
            <h2 class="mb-4">CONTACT DETAILS:</h2>
            <div class="mb-3">
                <h4>Address:</h4>
                <p>C/ Doctor Sapena, 25
                    <br>03013, Alicante (Spain)
                </p>
            </div>
            <div class="mb-4">
                <h4>Openning Times:</h4>
                <p>MON - SUN from <strong>17:00</strong> to <strong>23:00</strong></p>
            </div>
        </div>
        <div id="map" class="col-md-6 mt-4 mb-4 text-center">
            <h4>Location:</h4>
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3128.7858314136834!2d-0.4796923240891507!3d38.353938771845115!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd6237a641976135%3A0x87bad0160d0e0e88!2sCafeteria%20l&#39;alba!5e0!3m2!1ses!2ses!4v1703198291952!5m2!1ses!2ses"
                width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>


{% endblock %}

contact/templates/contact/success_message.html
{% extends 'base.html' %}

{% block content %}
    <div class="container success-container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-success" role="alert">
                    <h3 class="alert-heading">Your message has been sent successfully!</h3>
                    <p>We will get back to you as soon as possible.</p>
                    <hr>
                    <button class="btn btn-primary" onclick="goToHomePage()">Go to Home Page</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        function goToHomePage() {
            window.location.href = "{% url 'home' %}";
        }
    </script>
{% endblock %}